Algoritmo "número entre 20 e 90"
// Numero está compreendido entre 20 e 90?
Var
   numeroDigitado:real
Inicio
      escreval("Escreva um número e eu direi se ele está compreendido entre 20 e 90")
      leia(numeroDigitado)

      se (numeroDigitado >= 20) e (numeroDigitado <= 90) entao
      escreval("O número está compreendido entre 20 e 90")
      senao
      escreval("O número não está compreendido entre 20 e 90")
      fimse
Fimalgoritmo